export const ADD_AGE = 'ADD_AGE'
export const LOGIN = 'LOGIN'
export const TOKEN = 'TOKEN'
export const USER_ID = 'USER_ID'
export const SET_USER_LOGIN_NAME = 'SET_USER_LOGIN_NAME'
export const CLEAR_LOCALSTORAGE = 'CLEAR_LOCALSTORAGE'